server:
 port: 8091

springfox:
 title: 'FINT SSE Adapter Skeleton'
 version: '@version@'

fint:
 adapter:
  organizations: pwfa.no
  sse-endpoint: https://play-with-fint-adapter.felleskomponent.no/provider/sse/%s
  status-endpoint: https://play-with-fint-adapter.felleskomponent.no/provider/status
  response-endpoint: https://play-with-fint-adapter.felleskomponent.no/provider/response

