server:
  port: 8091

fint:
  adapter:
    organizations: pwfa.no
  base-url: https://play-with-fint-adapter.felleskomponent.no/provider

  oauth:
    enabled: false
#    username:
#    password:
#    client-id:
#    client-secret:
#    access-token-uri:
#    scope:
